stop using java clock in ScopedCache
zio/zio-cache pull request #134
Opened 2023-02-15 11:06 UTC by strokyl

2023-03-24 08:14 UTC, strokyl commented
UP

2023-03-24 09:03 UTC, guizmaii commented on zio-cache/shared/src/main/scala/zio/cache/ScopedCacheImplementation.scala
> +              if (now.isAfter(timeToLive)) {
@strokyl I think we're loosing a piece of information here. The code was super explicit before: `hasExpired(timeToLive)`

What do you think of doing this to keep the explicitness of what this code is testing:
```suggestion
              val hasExpired = now.isAfter(timeToLive)
              if (hasExpired) {
```

2023-03-24 09:03 UTC, guizmaii commented on zio-cache/shared/src/main/scala/zio/cache/ScopedCacheImplementation.scala
> +              if (now.isAfter(ttl)) {
Same suggestion

2023-03-24 09:04 UTC, guizmaii commented on zio-cache/shared/src/main/scala/zio/cache/ScopedCacheImplementation.scala
> +            if (now.isAfter(ttl)) {
Sam suggestion

2023-03-24 09:06 UTC, guizmaii commented
@adamgfraser Could you please have a look at this PR, please?

2023-03-24 20:50 UTC, adamgfraser requested changes
We should use the `unsafe` operators on `Clock` here so we retain the benefits of not having to evaluate a ZIO workflow to get the time while having the testability of being able to substitute our own implementation.

2023-04-04 09:59 UTC, strokyl commented
> We should use the `unsafe` operators on `Clock` here so we retain the benefits of not having to evaluate a ZIO workflow to get the time while having the testability of being able to substitute our own implementation.

Should be good now.

2023-04-04 17:19 UTC, adamgfraser requested changes
Would just provide the unsafe capability explicitly for internal code like this.

```scala
hasExpired(ttl)(Unsafe.unsafe)
```

instead of:

```scala
Unsafe.unsafe(hasExpired(ttl)(_))
```

Otherwise looks great!

2023-04-05 13:18 UTC, strokyl commented
> Would just provide the unsafe capability explicitly for internal code like this.
> 
> ```scala
> hasExpired(ttl)(Unsafe.unsafe)
> ```
> 
> instead of:
> 
> ```scala
> Unsafe.unsafe(hasExpired(ttl)(_))
> ```
> 
> Otherwise looks great!

Should be good now.

2023-04-05 23:54 UTC, adamgfraser approved these changes

2023-04-05 23:54 UTC, merged